### ISSUE TITLE
Asset: enable search by financial detail

### ISSUE THREAD

**Issue by livochka** [bulgarian-open-source/airport#14]
### Description
- [x] Enhance `Asset` with property `finDet`: `AssetFinDet`
- [x] Enhance Asset Centre selection criteria for:
- `finDet.initCost`
- `finDet.acquireDate`
- [x] Expose the sub-properties in the resultset

### Expected outcome
Ability to search and report assets by their financial details

**Comment by ipopovych** [comment]
@livochka you are a nice dog! 🐶
