### ISSUE TITLE
Create Entity `Project` for managing capital expenditures

### ISSUE THREAD

**Issue by mitryahina** [bulgarian-open-source/airport#15]
### Description
Entity Project is needed for managing capital expenditures including acquiring new assets and upgrading existing ones.

### Expected outcome
Entity `Project` is created, it is persistant and has the following properties:

- [x]  `name': String -- single key member which uniquely identifies the project

- [x] `desc` --  by using annotation `@DescRequired`

- [x]  `startDate`:Date -- `@DateOnly` `@Reqired` property that specifies the beginning of the  project

- [x]  `finishDate`:Date -- `@DateOnly` property that specifies the end of the project. Must be  afrter startDate

**Comment by mitryahina** [comment]
Issue resolved @ branch Issue#15

**Comment by livochka** [comment]
creation of the Project ends with java.lang.NullPointerException. @tanyayez can you look and fix it please?

**Comment by livochka** [comment]
project model created, errors fixed

**Comment by mitryahina** [comment]
Testing successfully passed.
