### ISSUE TITLE
Asset Type ownership with mutually exclusive owners model and UI

### ISSUE THREAD

**Issue by ipopovych** [bulgarian-open-source/airport#19]
### Description
- [x] Create ownership types: abstract persistent entities `Role`, `BusinessUnit` and `Organization` that should all have property `name`: `String`

- [x]  Create an entity `AssetTypeOwnership` with the following properties:

- a composite key member property `assetType`: `AssetType`

- a composite key member property `startDate`: `Date`

- properties which should be mutually exclusive:
      - property `role`: `Role`
      - property `bu`: `BusinessUnit`
      - property `org`: `Organization`

- [x]  Ensure that the `AssetType` could be associated with one owner at a time and cover the implemented functionality with tests

- [x] Create UI for managing Asset Type Ownerships:

- Create Asset Type Master.

- Create Asset Type Centre.

### Expected outcome
Users are able to record the Role, Business Unit or Organization that owns an Asset Type and Asset Type is associated to the applicable Asset Owner and the date/time of the association is recorded.

**Comment by ipopovych** [comment]
Need to implement also AssetTypeOwnershipExclusivityDefiner to check for exclusivity of the owner.

**Comment by ipopovych** [comment]
@livochka pls develop UI for the asset type ownership

**Comment by livochka** [comment]
@ipopovych  implemented

**Comment by livochka** [comment]
Decided to move implementation of similar functionality for an Asset into separate issue
