### ISSUE TITLE
Asset Financial Details include Project to which Asset may belong

### ISSUE THREAD

**Issue by mitryahina** [bulgarian-open-source/airport#21]
### Description
Enhance entity `AssetFinDet` with property `project: Project` to save information about the project for which the corresponding asset was acquired. This property is not required as the asset may be acquired independently of the capital expenditure project. 

In cases where project is specified the following integrity constraint should be applied:

- [x]   Property `AssetFinDet.acquireDate` should be within the project's period from Project.startDate to Project.finishDate, and this period should encompass all assets referencing the project.

Also as a convenience:

- [x]  Property ` AssetFinDet.acquireDate` should be defaulted to AssetFinDet.project.startDate if it was empty at the time of assigning the project

Property `AssetFinDet.acquireDate` requires a validator (i.e. BCE handler) to ensure the value assigned is within Project.startDate to Project.finishDate; this also means that the same validation should be performed when property `AssetFinDet.project` is changed.

Conversely, changes to `Project.startDate` and `Project.finishDate` should be validated against all instances of `AssetFinDet` referencing the project to ensure that the project period encompasses all those assets.

Property `AssetFinDet.project` should have a definer (i.e. ACE handler) to default `AssetFinDet.acquireDate` if it was empty to `AssetFinDet.project.startDate`.

### Expected outcome
Project is optionally assigned to an Asset as its FinDet property.

**Comment by livochka** [comment]
everything is great!

**Comment by livochka** [comment]
ready for merge

**Comment by livochka** [comment]
merged
