### ISSUE TITLE
Asset Type operatorship with mutually exclusive operators model and UI

### ISSUE THREAD

**Issue by ipopovych** [bulgarian-open-source/airport#23]
### Description
- [x]  Create an entity `AssetTypeOperatorship` with the following properties:

- a composite key member property `assetType`: `AssetType`

- a composite key member property `startDate`: `Date`

- properties which should be mutually exclusive:
      - property `role`: `Role`
      - property `bu`: `BusinessUnit`
      - property `org`: `Organization`

- [x]  Create an entity `AssetOperatorship` with similar properties

- [x]  Ensure that the `AssetType` could be associated with one operator at a time and cover the implemented functionality with tests

- [x] Create UI for managing Asset Type Operatorships:

- Create AssetType   Operatorship Master.

- Create AssetType   Operatorship Centre.

### Expected outcome
Users are able to record the Role, Business Unit or Organization that operates an Asset Type and Asset Type is associated with the applicable Asset Type Operator and the date/time of the association is recorded.

**Comment by ipopovych** [comment]
added AssetTypeOperatorship with UI and tests

**Comment by livochka** [comment]
Decided to move implementation of similar functionality for an Asset into separate issue
