### ISSUE TITLE
Asset service status model and UI 

### ISSUE THREAD

**Issue by livochka** [bulgarian-open-source/airport#24]
### Description

- [x]  Create an entity `AssetServiceStatus` with the following properties:

- a composite key member property `asset`: `Asset`

- a composite key member property `startDate`: `Date`

 - required property `serviceStatus`: `ServiceStatus`

- [x]  Cover the implemented functionality with tests

- [x] Create UI for managing Asset Service Status:

- Create  Asset Service Status Master.

- Create  Asset Service Status Centre.

### Expected outcome
 Asset  is associated to the applicable Asset Service Status and the date/time of the association is recorded.

**Comment by livochka** [comment]
@mitryahina please test it

**Comment by mitryahina** [comment]
Successfully merged
