### ISSUE TITLE
AssetOwnership, AssetManagement, AssetOperationship models and UIs

### ISSUE THREAD

**Issue by livochka** [bulgarian-open-source/airport#42]
### Description

- [ ]  Create an entities `AssetOwnership`,  `AssetOperationship`, `AssetManagement` with the following properties:

- a composite key member property `asset`: `Asset`

- a composite key member property `startDate`: `Date`

 -  mutually exclusive properties `role`: `Role`, `bu`: `BusinessUnit`, `org`: `Organization`

-  [ ]  Cover the implemented functionality with tests

-  [ ]  If none of `role`, `bu`, `org` was specified, set it default as in corresponding `AssetTypeOwnership` etc

- [ ] Create UI for managing `AssetOwnership`,  `AssetOperationship`, `AssetManagement`:

- Create Master.

- Create  Centre.

### Expected outcome
 Asset  is associated to the applicable organizational details and the date/time of the association is recorded.

**Comment by livochka** [comment]
Tried a bunch of approaches to set `role` , `bu` or `org` by default from AssetType, but failed because of the integrity constraints with meta-properties. Girls, any ideas?

**Comment by ipopovych** [comment]
I finished creating this functionality for `operatorship`
@livochka PTAL in [this branch](https://github.com/bulgarian-open-source/airport/tree/Issue%2333)
